alias fd='flutter devices'
alias zll='zellij ls'
alias zla='zellij a'
alias zld='zellij d'
alias cljd='clj -M:cljd'
alias info='info --vi-keys'
alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
hx 2> /dev/null || alias hx='helix'
