#colorscheme catppuccin_latte
colorscheme black-on-white

set-option global tabstop 2
set-option global indentwidth 2

add-highlighter global/ show-matching -previous
add-highlighter global/ show-whitespaces -lf "" -only-trailing
add-highlighter global/ number-lines -relative
add-highlighter global/ wrap -word -indent

declare-user-mode config-mode
map global user c ':enter-user-mode config-mode<ret>' -docstring 'config mode'
map global config-mode k ':edit ~/.config/kak/kakrc<ret>' -docstring 'edit kak config'
map global config-mode t ':edit ~/.tmux.conf<ret>' -docstring 'edit tmux config'
map global config-mode b ':edit ~/scripts/oh-my-bash.bash<ret>' -docstring 'edit bash config'

# no syntax highlighting cuz i'm not juvenile (lol)
set global disabled_hooks '.*-highlight'

# share yank register with tmux buffer
#hook global RegisterModified '"' %{ nop %sh{ tmux set-buffer -w -- "$kak_reg_dquote" } }

define-command yank-to-tmux-clipboard %{ nop %sh{ tmux set-buffer -w "$kak_selections" } }
map global user y ':yank-to-tmux-clipboard<ret>' -docstring 'yank to clipboard'

hook global FocusIn .* %{ echo -debug focus! } # doesn't work yet

# case insensitive search
hook global NormalKey (<a-[/?]>|[/?]) %{ execute-keys (?i) }
hook global NormalKey ([sS]|<a-[kK]>) %{ execute-keys (?i) } # idk why this doesn't work

define-command goto-file-line-column %{
    evaluate-commands %sh{
        printf 'edit %s' "$(printf '%s' $kak_selections | tr ':' ' ')"
    }
}
map global goto F '<esc>:goto-file-line-column<ret>' -docstring 'file[:line[:col]]'

map global normal <C-h> ':bp<ret>' -docstring 'previous buffer'
map global insert <C-h> '<esc>:bp<ret>' -docstring 'previous buffer'
map global normal <C-l> ':bn<ret>' -docstring 'next buffer'
map global insert <C-l> '<esc>:bn<ret>' -docstring 'next buffer'
map global normal <C-w> ':db<ret>' -docstring 'delete buffer'
map global insert <C-w> '<esc>:db<ret>' -docstring 'delete buffer'

# Bootstrap plug.kak
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "andreyorst/fzf.kak" config %{
#    hook global ModuleLoaded fzf-file %{
#        set-option global fzf_file_command 'rg' # 'ag', 'fd', or 'find'
#    }
    hook global ModuleLoaded fzf-file %{
        set-option global fzf_file_command 'find -type f ! -path \*/.\*' # 'ag', 'fd', or 'find'
    }
    map global user f ': fzf-mode<ret>' -docstring 'fzf mode'
    # don't know how to get this to load
    #    plug 'https://gitlab.com/losnappas/fzf-yank-ring.kak.git' load-path "%opt{plug_install_dir}/fzf.kak/rc/modules/"
}

plug 'https://git.sr.ht/~raiguard/kak-mirror' config %{
  map global normal "'" ': enter-user-mode -lock mirror<ret>'
}

plug "alexherbo2/auto-pairs.kak" config %{ enable-auto-pairs }

plug "occivink/kakoune-expand" config %{
    map -docstring "expand" global user e ': expand<ret>'

    # 'lock' mapping where pressing <space> repeatedly will expand the selection
    declare-user-mode expand
    map -docstring "expand"                     global expand <space> ': expand<ret>'
    map -docstring "expand ↻"                   global user   E       ': expand; enter-user-mode -lock expand<ret>'
    map -docstring "undo last selection change" global expand <a-u>   <a-u>
    map -docstring "redo last selection change" global expand <a-U>   <a-U>
}

plug "eko234/kakoune-recent-buffers" config %{
  declare-user-mode chain
  map global user r ": recent-buffers-pick-link<ret>" -docstring "recent buffers"
  map global user R ": enter-user-mode -lock chain<ret>" -docstring "chain mode"
  map global chain p ": recent-buffers-loose-chain<ret>" -docstring "loose"
  map global chain n ": recent-buffers-pull-chain<ret>" -docstring "pull"
}

##################################################
# git
##################################################

hook global WinCreate .* %{ git show-diff }
hook global BufWritePost .* %{ git update-diff }

plug 'https://git.sr.ht/~hadronized/git.kak' config %{
    map global user g ':enter-user-mode git<ret>' -docstring 'git mode'
    map global git h ':git log -p -- <c-r>%<ret>' -docstring 'file history'
}

##################################################
# Formatter
##################################################

## This doesn't work because lsp-formatting doesn't cause an error when an lsp isn't found
#define-command format-with-lsp-or-formatter -docstring "format with lsp or formatter" %{
#    try %{
#        lsp-formatting
#    } catch %{
#        format-buffer
#    }
#}

map global user <space> '<esc>:format-buffer<ret>' -docstring 'format buffer'

hook global BufSetOption filetype=cmake %{
    set-option buffer formatcmd "cmake-format -"
}

hook global BufSetOption filetype=sh %{
    set-option buffer formatcmd "shfmt"
}

hook global BufSetOption filetype=awk %{
    set-option buffer formatcmd "awk -o- -f -"
}

hook global BufSetOption filetype=toml %{
    set-option buffer formatcmd "taplo format -"
}

hook global BufSetOption filetype=yaml %{
    set-option buffer formatcmd "yamlfmt -in"
}

##################################################
# LSP
# https://github.com/kakoune-lsp/kakoune-lsp
##################################################

eval %sh{kak-lsp}
lsp-enable
map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'
map global insert <c-n> '<a-;>:lsp-snippets-select-next-placeholders<ret>' -docstring 'Select next snippet placeholder'

hook global InsertCompletionShow .* %{
  unmap global insert <c-n> '<a-;>:lsp-snippets-select-next-placeholders<ret>'
}

hook global InsertCompletionHide .* %{
  map global insert <c-n> '<a-;>:lsp-snippets-select-next-placeholders<ret>' -docstring 'Select next snippet placeholder'
}

#lsp-inlay-hints-enable global
#lsp-inlay-diagnostics-enable global

# Configure LSPs
# See: https://github.com/kakoune-lsp/kakoune-lsp/blob/master/rc/servers.kak

remove-hooks global lsp-filetype-.*

hook -group lsp-filetype-dart global BufSetOption filetype=dart %{
    set-option buffer lsp_servers %{
        [fvm-dart-lsp]
        root_globs = ["pubspec.yaml", ".git", ".hg"]
        command = "fvm"
        args = ["dart", "language-server"]
    }
}

hook -group lsp-filetype-cmake global BufSetOption filetype=cmake %{
    set-option buffer lsp_servers %{
        [cmake-language-server]
        root_globs = ["CMakeLists.txt", ".git", ".hg"]
        command = "neocmakelsp"
        args = ["stdio"]
    }
}

hook -group lsp-filetype-c-family global BufSetOption filetype=(?:c|cpp|objc) %{
    set-option buffer lsp_servers %{
        [clangd]
        args = ["--clang-tidy",
                "--header-insertion=iwyu",
                "--completion-style=detailed",
                "--function-arg-placeholders",
                "--log=verbose",
                "--enable-config"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    }
}
