set-option global tabstop 2
set-option global indentwidth 2

add-highlighter global/ show-matching -previous
add-highlighter global/ show-whitespaces -lf "" -only-trailing
add-highlighter global/ number-lines -relative
add-highlighter global/ wrap -word -indent

declare-user-mode config-mode
map global user c ':enter-user-mode config-mode<ret>' -docstring 'config mode'
map global config-mode k ':edit ~/.config/kak/kakrc<ret>' -docstring 'edit kak config'
map global config-mode t ':edit ~/.tmux.conf<ret>' -docstring 'edit tmux config'
map global config-mode b ':edit ~/scripts/oh-my-bash.bash<ret>' -docstring 'edit bash config'

# share yank register with tmux buffer
#hook global RegisterModified '"' %{ nop %sh{ tmux set-buffer -w -- "$kak_reg_dquote" } }

define-command yank-to-tmux-or-system-clipboard %{ nop %sh{
  if [ -n "$TMUX" ]; then
    # inside a tmux session
    tmux set-buffer -w "$kak_selections"
	elif command -v xsel >/dev/null; then
		# use xsel for system clipboard
		<<EOF xsel -ib
$kak_selections
EOF
  else
  	echo 'No system clipboard found' >&2
    exit 1
  fi
} }
map global user y ':yank-to-tmux-or-system-clipboard<ret>' -docstring 'yank to tmux or system clipboard'

# Reuse scratch buffer or create a new one
define-command scratch %{
  try %{
    buffer *scratch*
  } catch %{
    edit -scratch *scratch*
  }
}
map global user s ':scratch<ret>' -docstring 'Use scratch buffer'

# case insensitive search
hook global NormalKey (<a-[/?]>|[/?]) %{ execute-keys (?i) }
hook global NormalKey ([sS]|<a-[kK]>) %{ execute-keys (?i) } # idk why this doesn't work when combined with the line above

define-command goto-file-line-column %{
    evaluate-commands %sh{
        printf 'edit %s' "$(printf '%s' $kak_selections | tr ':' ' ')"
    }
}
map global goto F '<esc>:goto-file-line-column<ret>' -docstring 'file[:line[:col]]'

map global normal <C-h> ':bp<ret>' -docstring 'previous buffer'
map global insert <C-h> '<esc>:bp<ret>' -docstring 'previous buffer'
map global normal <C-l> ':bn<ret>' -docstring 'next buffer'
map global insert <C-l> '<esc>:bn<ret>' -docstring 'next buffer'
map global normal <C-w> ':db<ret>' -docstring 'delete buffer'
map global insert <C-w> '<esc>:db<ret>' -docstring 'delete buffer'

map global normal <C-a> ':comment-line<ret>' -docstring 'comment line'
map global insert <C-a> '<esc>:comment-line<ret>' -docstring 'comment line'
map global normal <C-A> ':comment-block<ret>' -docstring 'comment block'
map global insert <C-A> '<esc>:comment-block<ret>' -docstring 'comment block'

# Bootstrap plug.kak
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "catppuccin/kakoune" theme config %{
  colorscheme catppuccin_latte
}

plug "andreyorst/fzf.kak" config %{
    map global user f ': fzf-mode<ret>' -docstring 'fzf mode'
} defer fzf %{
    # set-option global fzf_preview_width '65%'
    # set-option global fzf_project_use_tilda true
  declare-option str fzf_file_command 'fd'
  declare-option str fzf_grep_command 'rg'
  # set-option global fzf_file_command 'fd' # 'ag', 'fd', or 'find'
  # set-option global fzf_grep_command 'rg' # 'ag', or 'find'
}

plug 'https://git.sr.ht/~raiguard/kak-mirror' config %{
  map global normal "'" ': enter-user-mode -lock mirror<ret>'
}

plug "alexherbo2/auto-pairs.kak" config %{ enable-auto-pairs }

plug "Delapouite/kakoune-text-objects"

##################################################
# git
##################################################

hook global WinCreate .* %{ git show-diff }
hook global BufWritePost .* %{ git update-diff }

plug 'https://git.sr.ht/~hadronized/git.kak' config %{
    map global user g ':enter-user-mode git<ret>' -docstring 'git mode'
    map global git h ':git log --date-order --date=iso --follow --patch -- <c-r>%<ret>' -docstring 'file history'
    map global git l ':git log --date-order --date=iso --full-history --all --graph<ret>' -docstring 'commit history'
}

##################################################
# Formatter
##################################################

## This doesn't work because lsp-formatting doesn't cause an error when an lsp isn't found
# define-command format-with-lsp-or-formatter -docstring "format with lsp or formatter" %{
#    try %{
#        lsp-formatting
#    } catch %{
#        format-buffer
#    }
# }

map global user <space> '<esc>:format-buffer<ret>' -docstring 'format buffer'

hook global BufSetOption filetype=cmake %{
    set-option buffer formatcmd "cmake-format -"
}

hook global BufSetOption filetype=sh %{
    set-option buffer formatcmd "shfmt"
}

hook global BufSetOption filetype=awk %{
    set-option buffer formatcmd "awk -o- -f -"
}

hook global BufSetOption filetype=toml %{
    set-option buffer formatcmd "taplo format -"
}

hook global BufSetOption filetype=yaml %{
    set-option buffer formatcmd "yamlfmt -in"
}

##################################################
# LSP
# https://github.com/kakoune-lsp/kakoune-lsp
##################################################

eval %sh{kak-lsp}
# lsp-enable
map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'
map global insert <c-n> '<a-;>:lsp-snippets-select-next-placeholders<ret>' -docstring 'Select next snippet placeholder'

hook global InsertCompletionShow .* %{
  unmap global insert <c-n> '<a-;>:lsp-snippets-select-next-placeholders<ret>'
}

hook global InsertCompletionHide .* %{
  map global insert <c-n> '<a-;>:lsp-snippets-select-next-placeholders<ret>' -docstring 'Select next snippet placeholder'
}

#lsp-inlay-hints-enable global
#lsp-inlay-diagnostics-enable global

# Configure LSPs
# See: https://github.com/kakoune-lsp/kakoune-lsp/blob/master/rc/servers.kak

remove-hooks global lsp-filetype-.*

hook -group lsp-filetype-dart global BufSetOption filetype=dart %{
    set-option buffer lsp_servers %{
        [fvm-dart-lsp]
        root_globs = ["pubspec.yaml", ".git", ".hg"]
        command = "fvm"
        args = ["dart", "language-server"]
    }
}

hook -group lsp-filetype-cmake global BufSetOption filetype=cmake %{
    set-option buffer lsp_servers %{
        [cmake-language-server]
        root_globs = ["CMakeLists.txt", ".git", ".hg"]
        command = "neocmakelsp"
        args = ["stdio"]
    }
}

hook -group lsp-filetype-c-family global BufSetOption filetype=(?:c|cpp|objc) %{
    set-option buffer lsp_servers %{
        [clangd]
        args = ["--clang-tidy",
                "--header-insertion=iwyu",
                "--completion-style=detailed",
                "--function-arg-placeholders",
                "--log=verbose",
                "--enable-config"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    }
}

hook -group lsp-filetype-ocaml global BufSetOption filetype=ocaml %{
    set-option buffer lsp_servers %{
        [ocamllsp]
        # Often useful to simply do a `touch dune-workspace` in your project root folder if you have problems with root detection
        root_globs = ["dune-workspace", "dune-project", "Makefile", "opam", "*.opam", "esy.json", ".git", ".hg", "dune"]
        settings_section = "_"
        [ocamllsp.settings._]
        # codelens.enable = false
    }
}
