source $VIMRUNTIME/defaults.vim

" relative line numbers
set number
set relativenumber

" highlight cursorline
set cursorline

" text wrap
set wrap

" searching ignores case
set ignorecase

" search subdirectories
"set path+=**

" display all matching files during tab complete
set wildmenu

" There are certain files that we would never want to edit with Vim.
" Wild menu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

set wildmode=list:full
set wildignorecase

set updatetime=100

" buffers can exist in background without being in a window
set hidden

"""""""""""
" vim-lsp "
"""""""""""

"if executable('pylsp')
"    " pip install python-lsp-server
"    au User lsp_setup call lsp#register_server({
"        \ 'name': 'pylsp',
"        \ 'cmd': {server_info->['pylsp']},
"        \ 'allowlist': ['python'],
"        \ })
"endif

"if executable('fvm')
"    au User lsp_setup call lsp#register_server({
"        \ 'name': 'dart',
"        \ 'cmd': {server_info->['fvm dart language-server']},
"        \ 'allowlist': ['dart'],
"        \ })
"endif
"
"function! s:on_lsp_buffer_enabled() abort
"    setlocal omnifunc=lsp#complete
"    setlocal signcolumn=yes
"    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
"    nmap <buffer> gd <plug>(lsp-definition)
"    nmap <buffer> gs <plug>(lsp-document-symbol-search)
"    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
"    nmap <buffer> gr <plug>(lsp-references)
"    nmap <buffer> gi <plug>(lsp-implementation)
"    nmap <buffer> gt <plug>(lsp-type-definition)
"    nmap <buffer> <leader>rn <plug>(lsp-rename)
"    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
"    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
"    nmap <buffer> K <plug>(lsp-hover)
"    nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
"    nnoremap <buffer> <expr><c-d> lsp#scroll(-4)
"
"    let g:lsp_format_sync_timeout = 1000
"    autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')
"    
"    " refer to doc to add more commands
"endfunction
"
"augroup lsp_install
"    au!
"    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
"    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
"augroup END

"""""""""""
" vim-lsc "
"""""""""""
let g:lsc_server_commands = {'dart': 'fvm dart language-server'}

" Use all the defaults (recommended):
"let g:lsc_auto_map = v:true

" ... or set only the commands you want mapped without defaults.
" Complete default mappings are:
let g:lsc_auto_map = {
    \ 'GoToDefinition': '<C-]>',
    \ 'GoToDefinitionSplit': ['<C-W>]', '<C-W><C-]>'],
    \ 'FindReferences': 'gr',
    \ 'NextReference': '<C-n>',
    \ 'PreviousReference': '<C-p>',
    \ 'FindImplementations': 'gI',
    \ 'FindCodeActions': 'ga',
    \ 'Rename': 'gR',
    \ 'ShowHover': v:true,
    \ 'DocumentSymbol': 'go',
    \ 'WorkspaceSymbol': 'gS',
    \ 'SignatureHelp': 'gm',
    \ 'Completion': 'completefunc',
    \}

"" Extras "
"
"" search down to subfolders
"set path+=**
"
"" autocompletion after TAB
"set wildmenu
"
"" There are certain files that we would never want to edit with Vim.
"" Wild menu will ignore files with these extensions.
"set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
"
"set wildmode=list:full
"set wildignorecase
"
"" If Vim version is equal to or greater than 7.3 enable undo file.
"" This allows you to undo changes to a file even after saving it.
"if version >= 703
"  set undodir=~/.vim/backup
"  set undofile
"  set undoreload=10000
"endif
"
"nnoremap <return> :noh<return>
"
"""""""
"" UI "
"""""""
"
"" disable vi compatibility
"set nocompatible
"
"" Disable auto commenting in a new line
"autocmd Filetype * setlocal formatoptions-=c formatoptions-=r  formatoptions-=o
"
"" automatically load changed files
"set autoread
"
"" auto-reload vimrc
"autocmd! bufwritepost vimrc source ~/.vim/vimrc
"
"" show the filename in the window title bar
"set title
"
"" set encoding
"set encoding=utf-8
"
"" directories for swp files
"set backupdir=~/.vim/backup
"set directory=~/.vim/backupf
"
"" display incomplete commands at the bottom
"set showcmd
"
"
"" be able to arrow key and backspace across newlines
"set whichwrap=bs<>[]
"
"" status bar
"set laststatus=2
"
"" remember last cursor position
"autocmd BufReadPost *
"	\ if line("'\"") > 0 && line("'\"") <= line("$") |
"	\ 	exe "normal g`\"" |
"	\ endif
"
"" show '> ' at the beginning of lines that are automatically wrapped
"set showbreak=>\ 
"
"" enable completion
"set ofu=syntaxcomplete#Complete
"
"" make laggy connections work faster
"set ttyfast
"
"" let vim open up to 100 tabs at once
"set tabpagemax=100
"
"" case-insensitive filename completion
"set wildignorecase
"
""""""""""""""
"" Searching "
""""""""""""""
"
"set hlsearch "when there is a previous search pattern, highlight all its matches
"set incsearch "incremental search
"set ignorecase "ignore case in search patterns
"set smartcase "override the 'ignorecase' option if the search has uppercase
"set gdefault "imply global for new searches
"
""""""""""""""
"" Indenting "
""""""""""""""
"
"" When auto-indenting, use the indenting format of the previous line
"set copyindent
"set shiftwidth=2
"" When on, a <Tab> in front of a line inserts blanks according to 'shiftwidth'.
"" 'tabstop' is used in other places. A <BS> will delete a 'shiftwidth' worth of
"" space at the start of the line.
"set smarttab
"" Copy indent from current line when starting a new line (typing <CR> in Insert
"" mode or when using the "o" or "O" command)
"set autoindent
"" Automatically inserts one extra level of indentation in some cases, and works
"" for C-like files
"set smartindent
"
"" Add json syntax highlighting
"au BufNewFile,BufRead *.json set ft=json syntax=javascript
