source $VIMRUNTIME/defaults.vim

" enable Man plugin
runtime! ftplugin/man.vim

" use space as leader
let mapleader = "\<Space>"

" automatically read files that has been changed
set autoread

" always a status line
set laststatus=2

" vertical rulers
set colorcolumn=81

" highlight trailing whitespace
highlight TrailingWhitespace ctermbg=red guibg=red
match TrailingWhitespace /\s\+$/

" lisp words treated specially as special forms
set lispwords+=define*

" netrw
let g:netrw_banner=0       " disable banner
let g:netrw_browse_split=4 " open in prior window
let g:netrw_altv=1         " open splits to the right
let g:netrw_liststyle=3    " tree view

" relative line numbers
set number
set relativenumber

" don't set line numbers in terminal mode
autocmd TerminalOpen * setlocal nonumber norelativenumber

" highlight cursorline
set cursorline

" text wrap
set wrap

" searching, ignore case unless uppercase
set ignorecase
set smartcase

" display all matching files during tab complete
set wildmenu

" There are certain files that we would never want to edit with Vim.
" Wild menu will ignore files with these extensions.
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

set wildmode=list:full
set wildignorecase

set updatetime=100

" buffers can exist in background without being in a window
set hidden

" make laggy connections work faster
set ttyfast

" If Vim version is equal to or greater than 7.3 enable undo file.
" This allows you to undo changes to a file even after saving it.
if version >= 703
  set undodir=~/.vim/backup
  set undofile
  set undoreload=10000
endif

" enable completion
set omnifunc=syntaxcomplete#Complete

" When auto-indenting, use the indenting format of the previous line
set copyindent
set shiftwidth=2
" When on, a <Tab> in front of a line inserts blanks according to 'shiftwidth'.
" 'tabstop' is used in other places. A <BS> will delete a 'shiftwidth' worth of
" space at the start of the line.
set smarttab
" Copy indent from current line when starting a new line (typing <CR> in Insert
" mode or when using the "o" or "O" command)
set autoindent
" Automatically inserts one extra level of indentation in some cases, and works
" for C-like files
set smartindent

" Add json syntax highlighting
au BufNewFile,BufRead *.json set ft=json syntax=javascript

"""""""
" lsp "
"""""""
"packadd lsp
"
"autocmd User LspAttached {
"  nnoremap <buffer> <silent> gd <cmd>LspGotoDefinition<cr>
"  nnoremap <buffer> <silent> K  <cmd>LspHover<cr>
"  nnoremap <buffer> <silent> [d <cmd>LspDiag prev<cr>
"  nnoremap <buffer> <silent> ]d <cmd>LspDiag next<cr>
"  nnoremap <buffer> <silent> <leader>r <cmd>LspRename<cr>
"  nnoremap <buffer> <silent> <leader>a <cmd>LspCodeAction<cr>
"  setlocal tagfunc=lsp#lsp#TagFunc
"  setlocal formatexpr=lsp#lsp#FormatExpr()
"}
"
"autocmd User LspDetached {
"  silent! unmap <buffer> gd
"  silent! unmap <buffer> K
"  silent! unmap <buffer> [d
"  silent! unmap <buffer> ]d
"  silent! unmap <buffer> <leader>r
"  silent! unmap <buffer> <leader>a
"}
"
"
"" Clangd language server
"call LspAddServer([#{
"      \    name: 'clangd',
"      \    filetype: ['c', 'cpp'],
"      \    path: 'clangd',
"      \    args: ['--background-index']
"      \  }])
"
"" Rust language server
"call LspAddServer([#{
"      \    name: 'rustlang',
"      \    filetype: ['rust'],
"      \    path: 'rust-analyzer',
"      \    args: [],
"      \    syncInit: v:true
"      \  }])
"
"" Javascript/Typescript language server
""call LspAddServer([#{
""	\    name: 'typescriptlang',
""	\    filetype: ['javascript', 'typescript'],
""	\    path: 'typescript-language-server',
""	\    args: ['--stdio'],
""	\  }])
"
"call LspOptionsSet(#{
"      \   aleSupport: v:false,
"      \   autoComplete: v:true,
"      \   autoHighlight: v:false,
"      \   autoHighlightDiags: v:true,
"      \   autoPopulateDiags: v:false,
"      \   completionMatcher: 'case',
"      \   completionMatcherValue: 1,
"      \   diagSignErrorText: 'E>',
"      \   diagSignHintText: 'H>',
"      \   diagSignInfoText: 'I>',
"      \   diagSignWarningText: 'W>',
"      \   echoSignature: v:false,
"      \   hideDisabledCodeActions: v:false,
"      \   highlightDiagInline: v:true,
"      \   hoverInPreview: v:false,
"      \   completionInPreview: v:false,
"      \   closePreviewOnComplete: v:true,
"      \   ignoreMissingServer: v:false,
"      \   keepFocusInDiags: v:true,
"      \   keepFocusInReferences: v:true,
"      \   completionTextEdit: v:true,
"      \   diagVirtualTextAlign: 'above',
"      \   diagVirtualTextWrap: 'default',
"      \   noNewlineInCompletion: v:false,
"      \   maxDiagnostics: 200,
"      \   omniComplete: v:null,
"      \   omniCompleteAllowBare: v:false,
"      \   onTypeFormatting: v:false,
"      \   outlineOnRight: v:false,
"      \   outlineWinSize: 20,
"      \   popupBorder: v:true,
"      \   popupBorderHighlight: 'Title',
"      \   popupBorderHighlightPeek: 'Special',
"      \   popupBorderSignatureHelp: v:false,
"      \   popupHighlightSignatureHelp: 'Pmenu',
"      \   popupHighlight: 'Normal',
"      \   semanticHighlight: v:true,
"      \   showDiagInBalloon: v:true,
"      \   showDiagInPopup: v:true,
"      \   showDiagOnStatusLine: v:false,
"      \   showDiagWithSign: v:true,
"      \   showDiagWithVirtualText: v:false,
"      \   showInlayHints: v:false,
"      \   showSignature: v:true,
"      \   showSignatureDocs: v:false,
"      \   snippetSupport: v:false,
"      \   ultisnipsSupport: v:false,
"      \   useBufferCompletion: v:false,
"      \   usePopupInCodeAction: v:false,
"      \   useQuickfixForLocations: v:false,
"      \   vsnipSupport: v:false,
"      \   bufferCompletionTimeout: 100,
"      \   customCompletionKinds: v:false,
"      \   completionKinds: {},
"      \   filterCompletionDuplicates: v:false,
"      \   condensedCompletionMenu: v:false,
"      \   documentationFormat: ['markdown', 'plaintext'],
"      \ })

"""""""""""
" vim-lsc "
"""""""""""
"let g:lsc_server_commands = {'dart': 'fvm dart language-server'}
"
"let g:lsc_enable_autocomplete = v:false
"
"" ... or set only the commands you want mapped without defaults.
"" Complete default mappings are:
"let g:lsc_auto_map = {
"    \ 'GoToDefinition': '<C-]>',
"    \ 'GoToDefinitionSplit': ['<C-W>]', '<C-W><C-]>'],
"    \ 'FindReferences': 'gr',
"    \ 'NextReference': '<C-n>',
"    \ 'PreviousReference': '<C-p>',
"    \ 'FindImplementations': 'gI',
"    \ 'FindCodeActions': 'ga',
"    \ 'Rename': 'gR',
"    \ 'ShowHover': v:true,
"    \ 'DocumentSymbol': 'go',
"    \ 'WorkspaceSymbol': 'gS',
"    \ 'SignatureHelp': 'gm',
"    \ 'Completion': 'completefunc',
"    \}

"""""""""""""""""""""""""""""
" handle large files in vim "
" generated by google ai
"""""""""""""""""""""""""""""

" Automatically optimize settings for files larger than 20MB
let g:large_file_limit = 1024 * 1024 * 20

augroup LargeFile
  autocmd!
  autocmd BufReadPre * let f=getfsize(expand("<afile>")) | if f > g:large_file_limit || f == -2 | call LargeFileSettings() | endif
augroup END

function! LargeFileSettings()
  " Disable swap file to avoid disk writing lag
  setlocal noswapfile
  " Disable undo history to save memory
  setlocal undolevels=-1
  " Disable line wrapping (saves massive CPU on long lines)
  setlocal nowrap
  " Disable syntax highlighting and filetype detection
  setlocal syntax=off
  setlocal filetype=
  " Disable event handling for faster loading
  setlocal eventignore=all
  " Optimize redraws
  setlocal lazyredraw
  " Open in read-only mode if you just need to look
  setlocal readonly
endfunction

