theme = "catppuccin_latte"

[editor]
line-number = "relative"
scroll-lines = 1
cursorline = true
true-color = true
auto-format = false
completion-timeout = 5
completion-trigger-len = 1
rulers = [81, 101, 121]
bufferline = "multiple"
color-modes = true
jump-label-alphabet = "fjdkslaruvneicmwoxpzqghtyb"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "position-percentage", "file-encoding", "file-type"]

[editor.file-picker]
hidden = false

[editor.lsp]
# display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
G = ":reset-diff-change"
A-x = "select_line_above"
C-w = ":buffer-close"
Y = "yank_joined"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.normal.space]
"space" = ":format"
"l" = ":lsp-workspace-command"
