use-grammars = { only = [
  "toml",
  "clojure",
  "python",
  "dart",
  "javascript",
  "html",
  "c",
  "cpp",
  "bash",
  "cmake",
  "md",
  "bash",
  "futhark",
  "scheme"
] }

# Steel Scheme

[[language]]
name = "scheme"
# language-id = "scheme"
scope = "source.scheme"
file-types = ["scm"]
language-servers = ["steel"]

[language-server.steel]
command = "steel-language-server"
args = []

# Futhark

[[language]]
name = "futhark"
language-id = "futhark"
scope = "source.futhark"
file-types = ["fut"]
indent = { tab-width = 2, unit = "  " }
comment-tokens = ["--"]
language-servers = ["futhark"]
grammar = "futhark"

[language-server.futhark]
command = "futhark"
args = ["lsp"]

[[grammar]]
name = "futhark"
source = { git = "https://github.com/wstevick/tree-sitter-futhark", rev = "22a55ba7dfef1dd7bbb2b0ccfe46be550519a5e1" }

# Clojure

[[language]]
name = "clojure"
language-id = "clojure"
file-types = ["cljc", "clj", "cljs", "cljd", "edn"]
roots = ["deps.edn"]
auto-format = true
language-servers = ["clojure-lsp"]
# formatter = { command = "zprint" }

[language-server.clojure-lsp]
command = "clojure-lsp"
args = ["listen"]

[[language]]
name = "c"
language-id = "c"
language-servers = [ "clangd-12" ]

[[language]]
name = "cpp"
language-id = "cpp"
language-servers = [ "clangd-12" ]
roots = [ ".git", "CMakeLists.txt" ]

[language-server.clangd-12]
command = "clangd-12"
args = [ "--enable-config" ]
# config = { fallbackflags = [ "-DUNIT_TESTING" ] }

[[language]]
name = "python"
language-id = "python"
file-types = ["py", "bend"]
formatter = { command = "black", args = ["-", "--quiet"] }

[[language]]
name = "bash"
language-id = "bash"
formatter = { command = "shfmt" }

[[language]]
name = "dart"
roots = [ "pubspec.yaml" ]

[language.debugger]
name = "dart"
transport = "stdio"
command = "flutter"
args = ["debug-adapter"]

[[language.debugger.templates]]
name = "launch"
request = "launch"
completion = [
  { name = "entrypoint", completion = "filename", default = "lib/main.dart" },
]
args = { program = "{0}" }

